### PR TITLE
K8s on vms for s3gw container

### PR DESCRIPTION
**Pull request by giubacc**
This is a very first draft for the [idea](https://github.com/aquarist-labs/s3gw-core/issues/17) of creating a set of tools for easing the build of an environment for the `s3gw` container.
I'm conscious that the work to be done is not negligible and the efforts too.
I think anyway, that the benefits of an approach like this, in the mid/long term could hopefully be greater than the efforts.
Said that, I'm here to promote a discussion, and ultimately to ask if you think this direction is worth.

Currently, this tool is able to:

- Create an empty Kubernetes cluster on a set of virtual machines, 1 admin and N workers.

What it will be required to do:

- Deploy Longhorn on Kubernetes
- Deploy a basic but complete `s3gw` application on Kubernetes

All this process should be reasonably and consistently customizable.

In this draft for the vms I used an Ubuntu 20.04 LTS image because it was more simple getting a working k8s cluster.
I think that we should try to support also OpenSUSE Leap.

Fixes: aquarist-labs/s3gw#17

### CODE REVIEW

**Comment by trociny** [comment]
I would prefer we create a separate repo for the container builder. It might include the ceph repository as a submodule though if we considered it would make the things be easier.

**Comment by giubacc** [comment]
> I would prefer we create a separate repo for the container builder. It might include the ceph repository as a submodule though if we considered it would make the things be easier.

Do you mean both `environment` and `build` directories? 
This leads to the question: what should [s3gw-core](https://github.com/aquarist-labs/s3gw-core) be used for?

**Comment by trociny** [comment]
I would have `aquarist-labs/ceph` for ceph(radosgw) with our patches and `aquarist-labs/s3gw-core` (or some other name) for the build/environment things. Though it is just my opinion.

**Comment by trociny** [comment]
Ah sorry, I was confused. Never mind.

**Comment by giubacc** [comment]
Update:

This PR is now feature complete for a minimum set of functionalities.
With this tool you can have a complete `K8s` cluster with `Longhorn` and `s3gw` on a bunch of vms.
I think the right direction will be to try to merge the `k3s` approach with this one and offer the user the chance to choose what environment spawn up with a common set of yaml(s).

**Comment by votdev** [comment]
Is it somehow possible to re-use the already existing K8s objects that we've created in the k3s dictionary. Most of the objects in your PR are duplicates. Regardless how the cluster is installed, the objects should be the same.

**Pull request merged**
