### PR TITLE
s3gw/tests: add rudimentary smoke tests and benchmark

### PR DESCRIPTION
**Pull request by jecluis**
These are to be run against a file based backend. As they stand, the access key and secret key are not configurable to support dbstore and the likes.

This is meant as something to be expanded on, instead of implementing a comprehensive solution right now.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by 0xavi0** [comment]
I've been testing and it works fine as an initial smoke and benchmark test.

I've added this:
```bash
finish() {
       rm -rf ${testpath}
       exit ${1}
}
```
and instead of calling exit I call finish, so the temp folder is removed, when the test is done.

When deleting a bucket works we should also remove the test bucket as part of the smoke test.

The warp benchmark works also, (sometimes I got seg faults), but also test buckets are not removed.
I guess that will be fixed when bucket deletion works.

So far, I find it useful as a starting point.

We could also maybe use the compare functionality in the warp tool to compare against known executions to see if performance is impacted. (Although this will all depend on the environment we run this, of course)

**Comment by jecluis** [comment]
> I've been testing and it works fine as an initial smoke and benchmark test.
> 
> I've added this:
> 
> ```shell
> finish() {
>        rm -rf ${testpath}
>        exit ${1}
> }
> ```
> 
> and instead of calling exit I call finish, so the temp folder is removed, when the test is done.

I understand your point, but I'm personally against removing test runs automatically. When things fail, it's useful to have something to go back to and look at.

> When deleting a bucket works we should also remove the test bucket as part of the smoke test.
> 
> I see deleting an object already works... I would also add a test for deleting an object as well.

Yeah, all that. Lets do that on the next PR and expand on this.


> The warp benchmark works also, (sometimes I got seg faults), but also test buckets are not removed. I guess that will be fixed when bucket deletion works.

In this case we're explicitly not removing the test bucket (see `--noclear` option passed). My reasoning is that this is to be performed against ephemeral test instances of radosgw, so removing the buckets would simply be wasting time.

> So far, I find it useful as a starting point.
> 
> We could also maybe use the compare functionality in the warp tool to compare against known executions to see if performance is impacted. (Although this will all depend on the environment we run this, of course)

Yeah, this would be cool :)

**Comment by giubacc** [comment]
I think these scripts should be documented with a README.md explaining what are they intended for.
A minimal usage scenario should be provided to the user.
Also if there are some execution requirements these should be listed.

Eg: trying to execute `./s3gw-bench.sh` I'm getting:
```
error: unable to find 'warp' at '/home/giuseppe/go/bin'
consider installing with 'go install github.com/minio/warp@latest'
```
Also, running: `./s3gw-s3tests.sh` prints:
```
usage: ./s3gw-s3tests.sh HOST[:PORT]
```
this is a too much cryptic usage hint without a README.md because the user doesn't know what service/port should be used here.

**Comment by 0xavi0** [comment]
>

**Comment by 0xavi0** [comment]
> I understand your point, but I'm personally against removing test runs automatically. When things fail, it's useful to have something to go back to and look at.

Yeah, I also think it's useful to have that when a test fails. We could just check if it failed, and if so, then avoid cleaning.

My point of cleaning stuff is for when running this locally, when developing, to see if a change is breaking something. 
And to ensure that the state for every test execution is the same. 
We can, anyway, clean the state manually in between executions.

**Comment by jecluis** [comment]
@0xavi0 @giubacc pushed a README. Can we merge this?

**Comment by giubacc** [comment]
let me give a try of the whole thing, I will merge afterwards.

**Comment by 0xavi0** [comment]
I think we can merge and start using it.
I would also mention in the README file that the access and secret keys should be `test` when running the gw, but LGTM.

**Comment by giubacc** [comment]
ok, as said to @jecluis , we can think to make some argument customizable someway in the future (or not :).
LGTM.

**Review by 0xavi0 — APPROVED** [review]
I've tested the smoke test against `DBStore` and it passed. 
LGTM

**Pull request merged**
