### PR TITLE
k3s: Make sure open-iscsi is installed

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by jecluis** [comment]
I didn't seem to need this to run rgw on a PVC. What's the rationale behind installing iscsi on the cluster?

**Comment by votdev** [comment]
> I didn't seem to need this to run rgw on a PVC. What's the rationale behind installing iscsi on the cluster?

Without open-iscsi package installed on my host Longhorn will not be deployed at all and will get stuck at deploying the `longhorn-manager-xxx` pod.

**Comment by votdev** [comment]
According to the docs Longhorn requires open-iscsi, see https://longhorn.io/docs/1.2.4/deploy/install/#installation-requirements.

**Comment by votdev** [comment]
To be exactly, it's the `longhorn-iscsi-installation` daemonset.

```
$ kubectl describe ds longhorn-iscsi-installation
Name:           longhorn-iscsi-installation
Selector:       app=longhorn-iscsi-installation
Node-Selector:  <none>
Labels:         app=longhorn-iscsi-installation
Annotations:    command:
                  OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f...
                deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 1
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=longhorn-iscsi-installation
  Init Containers:
   iscsi-installation:
    Image:      alpine:3.12
    Port:       <none>
    Host Port:  <none>
    Command:
      nsenter
      --mount=/proc/1/ns/mnt
      --
      bash
      -c
      OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f 2); fi; if [[ "${OS}" == *"debian"* ]]; then sudo apt-get update -q -y && sudo apt-get install -q -y open-iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid; elif [[ "${OS}" == *"suse"* ]]; then sudo zypper --gpg-auto-import-keys -q refresh && sudo zypper --gpg-auto-import-keys -q install -y open-iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid; else sudo yum makecache -q -y && sudo yum --setopt=tsflags=noscripts install -q -y iscsi-initiator-utils && echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid; fi && if [ $? -eq 0 ]; then echo "iscsi install successfully"; else echo "iscsi install failed error code $?"; fi
    Environment:  <none>
    Mounts:       <none>
  Containers:
   sleep:
    Image:        k8s.gcr.io/pause:3.1
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:           <none>
```

**Review by giubacc — APPROVED** [review]

**Comment by votdev** [comment]
> > I didn't seem to need this to run rgw on a PVC. What's the rationale behind installing iscsi on the cluster?
> 
> Without open-iscsi package installed on my host Longhorn will not be deployed at all and will get stuck at deploying the `longhorn-manager-xxx` pod. The warning is about a failed readiness or liviness probe that exactly checks for the open-iscsi installation.

**Pull request merged**
