### PR TITLE
k3s: Use prefix to access S3 API and Longhorn UI

### PR DESCRIPTION
**Pull request by votdev**
- Use the prefix /longhorn to access the Longhorn UI via http://localhost:80/longhorn
- Use the prefix /s3gw to access the S3 API via localhost:80/s3gw
- Add configuration file for s3cmd in the ./k3s directory to allow running the command easily with the correct settings to access the s3gw in the local K3s cluster.

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by votdev** [comment]
Please note, you need to use the URL `localhost/longhorn/`. Somehow `localhost/longhorn` does not work. Any help is welcome.

**Comment by jecluis** [comment]
> Please note, you need to use the URL `localhost/longhorn/`. Somehow `localhost/longhorn` does not work. Any help is welcome.

This might have something to do with the `forceSlash` option being `false`?

Also, I don't think it's a great idea to have the `.s3.conf` file added to the repo, especially as a hidden file. While those configs will apply to access the cluster, the address bits might not be the same (e.g., I do run the cluster on a remote box). It's preferable to keep the configuration file as an example one in the repo, and let the user deal with that.

**Comment by giubacc** [comment]
I Agree with Joao it's not a good idea having `s3cmd` config file committed.
For the slash related question I don't have ideas atm; btw I'm doing some ingress experiment with `nginx` and I will let you know how this is behaving.

**Comment by votdev** [comment]
> This might have something to do with the forceSlash option being false?

No, this is not the reason, i've tested that. Setting `forceSlash` to false is recommended in the [documentation](https://doc.traefik.io/traefik/middlewares/http/stripprefix/#forceslash). The flag is responsible for how a URL looks like after stripping the prefix. We need to check how RGW bahaves if a path is '' or '/'. But i did not realize any issues while testing with the current setup.

**Comment by votdev** [comment]
> Also, I don't think it's a great idea to have the `.s3.conf` file added to the repo, especially as a hidden file. While those configs will apply to access the cluster, the address bits might not be the same (e.g., I do run the cluster on a remote box). It's preferable to keep the configuration file as an example one in the repo, and let the user deal with that.

I can not agree with that because if you install k3s according to the setup.sh script, the s3cmd config will match the cluster. If you are using a remote host, you surely did a git checkout there or transferred the k3s directory to that system. In both cases you can run the `s3cmd` from within the directory and the command will succeed because the .s3cfg file contains the necessary data that matches the cluster that was installed with `setup.sh`.

We can rename the file to whatever if you do not like a dot file.

**Comment by giubacc** [comment]
> We can rename the file to whatever if you do not like a dot file.

Maybe we can just document in the readme what this configuration file is for.
Could not be obvious for the user that a `s3cmd` tool exists.

**Pull request merged**
