### PR TITLE
Add README how to use the s3gw-ui container.

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by votdev** [comment]
@m-ildefons Are you missing more information?

**Review by jecluis — APPROVED** [review]
I think the README should have more information about building and running the container, but assuming that will eventually be provided I'm okay with it.

**Review by m-ildefons — CHANGES_REQUESTED** [review]
Yes. This does not tell me how to configure the ui to be able to connect to the s3gw (assuming non-default credentials) or what the other settings in the proxy.conf.json would do. If that information is irrelevant because it's not working atm anyways, I can live with it.
But this information [belongs in different place](https://github.com/aquarist-labs/s3gw/tree/main/docs), because a hand full of readmes distributed over several directories in several repositories is not a good documentation.

**Comment by jhmarina** [comment]
@jecluis I believe such documentation already exists here: https://github.com/aquarist-labs/s3gw/tree/main/docs - which is rendered here: https://s3gw-docs.readthedocs.io/en/latest/

**Pull request closed without merging**
